version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  apt_packages:
    - openjdk-11-jdk

sphinx:
   configuration: docs/source/conf.py

python:
   install:
     - method: pip
       path: .
       extra_requirements: 
         - docs