name: tests
on:
  - push
  - pull_request
jobs: 
  test:
    name: testing python versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - version: "3.7"
            toxenv: py37
          - version: "3.8"
            toxenv: py38
          - version: "3.9"
            toxenv: py39
          - version: "3.10"
            toxenv: py310
          - version: "3.11"
            toxenv: py311
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: 
          python-version: ${{ matrix.python.version }}
      - name: install tox
        run: pip install tox 
      - name: test with tox
        run: tox -e ${{ matrix.python.toxenv }}